FROM node:20-slim
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Génération de la structure du projet
RUN node generateStructureProject.js

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]